INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES('user','password', true);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES('foo','bar', true);

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('user','ROLE_USER');

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('foo','ROLE_ADMIN');